CLASS zbp_i_prepayment_preview DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_prepayment_preview.

PUBLIC SECTION.
CLASS-DATA gt_entry TYPE TABLE FOR ACTION IMPORT i_journalentrytp~post.
ENDCLASS.



CLASS ZBP_I_PREPAYMENT_PREVIEW IMPLEMENTATION.
ENDCLASS.
