    CLASS zcl_billing_split_static_var DEFINITION
      PUBLIC
      FINAL
      CREATE PRIVATE .

      PUBLIC SECTION.
        CLASS-DATA: mv_shared_value TYPE string.
      PROTECTED SECTION.
      PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_BILLING_SPLIT_STATIC_VAR IMPLEMENTATION.
ENDCLASS.
